DROP TABLE IF EXISTS CHARACTER;
CREATE TABLE IF NOT EXISTS CHARACTER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_name VARCHAR(64) NOT NULL,
    char_name VARCHAR(64) NOT NULL,
    title VARCHAR(64) DEFAULT '',
    race TINYINT DEFAULT 0,
    class_id TINYINT DEFAULT 0,
    access_level INT DEFAULT 0,
    online BOOLEAN DEFAULT FALSE,
    char_slot TINYINT DEFAULT 0,
    level INT DEFAULT 1,
    hp INT DEFAULT 1,
    max_hp INT DEFAULT 1,
    cp INT DEFAULT 1,
    max_cp INT DEFAULT 1,
    mp INT DEFAULT 1,
    max_mp INT DEFAULT 1,
    acc INT DEFAULT 1,
    critical INT DEFAULT 1,
    evasion INT DEFAULT 1,
    m_atk INT DEFAULT 1,
    m_def INT DEFAULT 1,
    m_spd INT DEFAULT 1,
    p_atk INT DEFAULT 1,
    p_def INT DEFAULT 1,
    p_spd INT DEFAULT 1,
    run_spd INT DEFAULT 1,
    walk_spd INT DEFAULT 1,
    str TINYINT DEFAULT 1,
    con TINYINT DEFAULT 1,
    dex TINYINT DEFAULT 1,
    _int TINYINT DEFAULT 1,
    men TINYINT DEFAULT 1,
    wit TINYINT DEFAULT 1,
    face TINYINT DEFAULT 0,
    hair_style TINYINT DEFAULT 0,
    hair_color TINYINT DEFAULT 0,
    sex TINYINT DEFAULT 0,
    heading FLOAT DEFAULT 0,
    x FLOAT DEFAULT 0,
    y FLOAT DEFAULT 0,
    z FLOAT DEFAULT 0,
    colR FLOAT DEFAULT 0,
    colH FLOAT DEFAULT 0,
    exp BIGINT DEFAULT 0,
    sp BIGINT DEFAULT 0,
    karma INT DEFAULT 0,
    pvp_kills INT DEFAULT 0,
    pk_kills INT DEFAULT 0,
    clan_id INT,
    max_weight INT DEFAULT 0,
    online_time BIGINT DEFAULT 0, 
    last_login BIGINT DEFAULT 0,
    delete_time BIGINT
);