-- SELECT NPCS THAT WERE NOT ADDED
SELECT DISTINCT n.CLASS 
FROM L2J_SPAWNLIST ljs 
INNER JOIN NPC n ON n.IDTEMPLATE = ljs.NPC_TEMPLATEID
WHERE 
    (ljs.LOCATION LIKE '%1624%' OR
    ljs.LOCATION LIKE '%1724%' OR
    ljs.LOCATION LIKE '%1625%')
    AND n.CLASS NOT IN (
        SELECT DISTINCT n_inner.CLASS 
        FROM L2J_SPAWNLIST ljs_inner 
        INNER JOIN NPC n_inner ON n_inner.IDTEMPLATE = ljs_inner.NPC_TEMPLATEID
        WHERE 
        ljs_inner.LOCATION LIKE '%1725%'
    );


-- SELECT ALL NPCS FOR GIVEN MAPS
SELECT DISTINCT n.CLASS 
FROM L2J_SPAWNLIST ljs 
INNER JOIN NPC n ON n.IDTEMPLATE = ljs.NPC_TEMPLATEID
WHERE 
    (ljs.LOCATION LIKE '%1624%' OR
    ljs.LOCATION LIKE '%1724%' OR
    ljs.LOCATION LIKE '%1625%' OR
    ljs.LOCATION LIKE '%1725%');